os: osx
language: objective-c
osx_image: xcode10.3

install:
  - bundle install

jobs:
  include:
    - stage: test
      if: branch = add-fastlane
      script: bundle exec fastlane tests
      #      deploy:
      # provider: script
      # script: bundle exec fastlane tests
      # on:
      #   branch: add-fastlane
      #   condition: $TRAVIS_BRANCH = add-fastlane

