default_platform(:ios)

platform :ios do
  desc "Testing application"
  lane :tests do
    cocoapods
    run_tests(workspace: "Sigma.xcworkspace",
              devices: ["iPhone 7", "iPad Air"],
              scheme: "SigmaTests")
  end
end
